// GENERATED BY HAND AS A PLACEHOLDER. RUN `flutterfire configure` TO REGENERATE.
// ignore_for_file: prefer_const_constructors, lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Temporary Firebase configuration so the project compiles.
/// Replace every value with the output from `flutterfire configure` for your
/// Firebase project (SmartDrive) before shipping.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOCeiw1sGPRzhhK4EpsjNNpjMRI82qXc',
    appId: '1:400113648098:web:08686ce2e61ebe12e539bb',
    messagingSenderId: '400113648098',
    projectId: 'smartdrive-dc55d',
    authDomain: 'smartdrive-dc55d.firebaseapp.com',
    storageBucket: 'smartdrive-dc55d.firebasestorage.app',
    measurementId: 'G-X37SSY8VZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EEH7vkcHvZa7v2QGMMb6jrEhr2saOdw',
    appId: '1:400113648098:android:e3ad0c5432888824e539bb',
    messagingSenderId: '400113648098',
    projectId: 'smartdrive-dc55d',
    storageBucket: 'smartdrive-dc55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOUycJG9hwmTICLA_YHlinETg4_lWNpw',
    appId: '1:400113648098:ios:df1ec37428ff6436e539bb',
    messagingSenderId: '400113648098',
    projectId: 'smartdrive-dc55d',
    storageBucket: 'smartdrive-dc55d.firebasestorage.app',
    iosBundleId: 'com.example.smartdrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOUycJG9hwmTICLA_YHlinETg4_lWNpw',
    appId: '1:400113648098:ios:df1ec37428ff6436e539bb',
    messagingSenderId: '400113648098',
    projectId: 'smartdrive-dc55d',
    storageBucket: 'smartdrive-dc55d.firebasestorage.app',
    iosBundleId: 'com.example.smartdrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyOCeiw1sGPRzhhK4EpsjNNpjMRI82qXc',
    appId: '1:400113648098:web:4f88935da4bcf4ebe539bb',
    messagingSenderId: '400113648098',
    projectId: 'smartdrive-dc55d',
    authDomain: 'smartdrive-dc55d.firebaseapp.com',
    storageBucket: 'smartdrive-dc55d.firebasestorage.app',
    measurementId: 'G-WTHZLS6PD7',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'LINUX_API_KEY',
    appId: 'LINUX_APP_ID',
    messagingSenderId: 'LINUX_SENDER_ID',
    projectId: 'smartdrive-placeholder',
    storageBucket: 'smartdrive-placeholder.appspot.com',
  );
}